---

- name: Set provisioning templates
  loop: "{{ foreman_os_provisioning_templates[os_family.key] }}"
  loop_control:
    label: "{{ item.name }}"
  theforeman.foreman.provisioning_template:
    operatingsystems: "{{ os_family.value }}"
    name: "{{ item.name }}"
    kind: "{{ item.kind }}"
    locations: "{{ item.locations }}"
    organizations: "{{ item.organizations }}"
    state: "present"
    validate_certs: "{{ foreman_cert_validation }}"
    server_url: "https://{{ foreman_host_name }}"
    username: "{{ foreman_default_user }}"
    password: "{{ foreman_default_password }}"

...
