---

- name: Set os default templates
  loop: "{{ foreman_os_default_templates[os.family] }}"
  loop_control:
    loop_var: os_default_template
    label: "{{ os_default_template.provisioning_template }}"
  theforeman.foreman.os_default_template:
    operatingsystem: "{{ os.description }}"
    provisioning_template: "{{ os_default_template.provisioning_template }}"
    template_kind: "{{ os_default_template.template_kind }}"
    state: "present"
    validate_certs: "{{ foreman_cert_validation }}"
    server_url: "https://{{ foreman_host_name }}"
    username: "{{ foreman_default_user }}"
    password: "{{ foreman_default_password }}"

...
