---

- hosts: all
  pre_tasks:
    - name: Display all parameters known for the Foreman host
      debug:
        var: foreman
      tags:
        - always
  tasks:
    - name: Apply roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      tags:
        - always
      loop: "{{ foreman_ansible_roles }}"
      loop_control:
        loop_var: role

    - name: Include users vars
      ansible.builtin.include_vars:
        file: "{{ local_users_file_path }}"

    - name: Get desktop users
      ansible.builtin.set_fact:
        desktop_users: "{{ users | selectattr('desktop', 'equalto', true) | map(attribute='name') | list }}"

...
